### ISSUE TITLE
Is this installing Hyperion on the rpi where hassio is running?

### ISSUE THREAD

**Issue by sunsgs** [bradsjm/hassio-addons#1]

**Comment by bradsjm** [comment]
Yes, this is a hassio addon that allows you to run Hyperion on the same box as Hassio. I do not have any LEDs directly connected as I use WLED and the native Android capture application but it seems it does work with SPI devices from one user in the forum.

There is a forum thread here: https://community.home-assistant.io/t/home-assistant-add-on-hyperion-ng/226850
