### ISSUE TITLE
upgrade addon build

### ISSUE THREAD

**Issue by danyboy666** [bradsjm/hassio-addons#10]
Improvement proposal: 
Would it be possible to upgrade container image for the latest hyperion.ng build?

```
Added
WLED: Support storing/restoring state, fixes #1101
```

I've tested it and it's working as expected so I would like to move my hyperion.ng rpi setup to my hassio vm installation.

**Comment by bradsjm** [comment]
The add-on uses the binary package releases (.deb) and does not compile from source so they need to release a new build with new binaries to be able to update it :(

**Comment by danyboy666** [comment]
Alright I'll wait for it i guess thanks

**Comment by danyboy666** [comment]
This issue solved itself with the last pkg update.
