### ISSUE TITLE
Hyperion docker add amd64 support?

### ISSUE THREAD

**Issue by That-Dude** [bradsjm/hassio-addons#14]
I've recently moved from a Pi4 to a NUC and would love to use your docker on amd64.

I've added the repository and the log file acknowledged the new git as expected:

`21-12-12 18:56:47 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/bradsjm/hassio-addons repository`

But the Hyperion add-on does not show up for selection at the bottom of the Add-on Store as expected.

**Comment by silfa718** [comment]
As a NUC user I would be interested as well.
