### ISSUE TITLE
Unable to pass values to v4l2

### ISSUE THREAD

**Issue by panec** [bradsjm/hassio-addons#3]
Thank you for including v4l-utils package as now I can modify the values for the default video device. I'm using a camera as my grabber which is working fine but I need to modify some values to make it respond faster. What I'm using now are those values:
`v4l2-ctl -c auto_exposure=1 -c white_balance_auto_preset=3 -c iso_sensitivity_auto=0 -c exposure_metering_mode=2`
but to call this I need to log into docker container and call it from there. Ideally, I would like to have a parameter in HA plugin config page to do it. If you could add it, it would be great.

**Comment by bradsjm** [comment]
That sounds like a great idea, I will see what I can come up with for the next release

**Comment by panec** [comment]
@bradsjm Any progress in the matter? It soon will be an anniversary of the ticket :)
