### ISSUE TITLE
Invalid slug using hassio.addon_start

### ISSUE THREAD

**Issue by shado214** [bradsjm/hassio-addons#6]
Hey, it seems the slug format is not valid for hassio.addon_start to use. Currently it's: dba1ceb5_hyperion.ng and it is not accepting it when I test it out in developer tools. Could you remove the ".ng" which is what I believe is causing the issue. Thx. Awesome job btw!
<img width="460" alt="Capture" src="https://user-images.githubusercontent.com/76407241/107179531-b492ba80-69a4-11eb-9aa9-9abfc6e6b68d.PNG">

**Comment by bradsjm** [comment]
I've just changed it in the source code here to a dash, will that work?

**Comment by shado214** [comment]
Hey thx for the quick response. Unfortunately it doesn't work with a dash. In the screenshot above, it suggest to use an underscore instead. I've used the service with other addons and it works when the addon name is only one word. Would it be possible to use "**dba1ceb5_hyperionng**"? Thx again!

**Comment by bradsjm** [comment]
No problem, try now

**Comment by shado214** [comment]
Hey, I just tried and it works perfectly now!! Thx a lot!
