### ISSUE TITLE
Deprecated terms in config

### ISSUE THREAD

**Issue by shado214** [bradsjm/hassio-addons#7]
Hey, I noticed something when I was randomly looking at my logs. It seems that "auto_uart" and "devices" in config are deprecated. Everything is working fine though.
<img width="557" alt="capture" src="https://user-images.githubusercontent.com/76407241/107539323-d81b5800-6b92-11eb-8604-9966a1597925.png">

**Comment by bradsjm** [comment]
Thanks, I've updated those config settings to use the new formats
