### ISSUE TITLE
Home Assistant Core 2021.2.3 update LED Bug

### ISSUE THREAD

**Issue by isibizi** [bradsjm/hassio-addons#9]
Hello,

today i have installed the core update 2021.2.3. After the update my leds turn off, on, off, on and so on.

My brother has the same bug after the update. My brother and i have an rpi4

Does anyone have the same problem?

**Comment by hm1234** [comment]
can confirm on the latest beta build of homeassistant having the same issue of the leds turning on and off

**Comment by isibizi** [comment]
The problem is not the core, the problem is OS version >5.10
